name: Push Dev Docker Image

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create secrets.properties
        run: |
          cd ./src/main/resources
          touch ./secrets.properties
          echo "${{ secrets.DEV_SECRETS_PROPERTIES }}" > ./secrets.properties
        shell: bash
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/proreviewer-back:dev